export enum ConflictErrorCodes {
  'INVITER_ALREADY_REGISTERED' = 'INVITER_ALREADY_REGISTERED',
}

export enum BadRequestErrorCodes {
  'INVITER_AND_INVITEE_ARE_SAME' = 'INVITER_AND_INVITEE_ARE_SAME',
  'REWARD_DETAIL_NOT_ABLE_TO_REMOVE' = 'REWARD_DETAIL_NOT_ABLE_TO_REMOVE',
  'ALREADY_REGISTERED_AS_INVITEE' = 'ALREADY_REGISTERED_AS_INVITEE',
}

export enum NotFoundErrorCodes {
  'ACQUAINTANCE_INVITATION_NOT_FOUND' = 'ACQUAINTANCE_INVITATION_NOT_FOUND',
  'INVITER_NOT_FOUND' = 'INVITER_NOT_FOUND',
  'REWARD_DETAILS_NOT_FOUND' = 'REWARD_DETAILS_NOT_FOUND',
}
